"""API request and response shapes.

One module per area rather than one file for everything: the models for a feature
live next to each other, and a change to the wizard cannot accidentally touch the
card browser. Everything is re-exported here, so no call site had to change.

Responses are camelCase on the wire and snake_case in Python; requests reject
unknown fields, so a client typo is an error rather than a silent no-op.
"""

from .availability import (
    AvailabilityUpdate,
    AvailabilityView,
    ExcludedCardView,
    ExclusionRuleInput,
    ExclusionRuleView,
    ForgetResult,
)
from .base import (
    ApiModel,
    StrictRequest,
)
from .card_meta import (
    CardDetailView,
    CardHomeView,
    CardPartnerView,
    CardPointView,
    CardTrendOverviewView,
    CardTrendView,
)
from .cards import (
    CardAvailabilityView,
    CardPage,
    CardView,
    PrintingView,
)
from .data import (
    BundleView,
    SourceHealthView,
)
from .decks import (
    BuildSuggestionsView,
    ChampionOptionView,
    CostView,
    CoverageView,
    DeckPayload,
    DeckSummaryView,
    DeckView,
    FieldMatchView,
    FormatView,
    IssueView,
    SuggestionView,
    ValidationView,
)
from .meta import (
    ArchetypeView,
    AttributionView,
    CardAdoptionView,
    ChampionMetaView,
    EraView,
    LegendMetaView,
    MetaDeckView,
    MetaStatusView,
    PairingView,
    PerformanceBasisView,
    PerformanceView,
    ProvenanceView,
    RankView,
    RefreshRunView,
    RefreshStatusView,
    ScoreView,
    TournamentDetailView,
    TournamentEntityView,
    TournamentView,
    TrendDeckView,
    TrendOverviewView,
    TrendPointView,
    TrendSeriesView,
)
from .scoring import DeckScoreView
from .smart_decks import (
    AcceptRequest,
    AnswerRequest,
    BanNoticeView,
    DeclinedCardView,
    DeclineRequest,
    FloorView,
    GapView,
    LegendChoiceView,
    ProposalView,
    QuestionView,
    RepairDeckCardView,
    RepairView,
    RequirementRowView,
    SaveCollectionRequest,
    SaveCollectionResult,
    SmartSessionView,
    StartSessionRequest,
    SwapView,
)

__all__ = [
    "AcceptRequest",
    "AnswerRequest",
    "ApiModel",
    "ArchetypeView",
    "AttributionView",
    "AvailabilityUpdate",
    "AvailabilityView",
    "BanNoticeView",
    "BuildSuggestionsView",
    "BundleView",
    "CardAdoptionView",
    "CardAvailabilityView",
    "CardDetailView",
    "CardHomeView",
    "CardPage",
    "CardPartnerView",
    "CardPointView",
    "CardTrendOverviewView",
    "CardTrendView",
    "CardView",
    "ChampionMetaView",
    "ChampionOptionView",
    "CostView",
    "CoverageView",
    "DeckPayload",
    "DeckScoreView",
    "DeckSummaryView",
    "DeckView",
    "DeclineRequest",
    "DeclinedCardView",
    "EraView",
    "ExcludedCardView",
    "ExclusionRuleInput",
    "ExclusionRuleView",
    "FieldMatchView",
    "FloorView",
    "ForgetResult",
    "FormatView",
    "GapView",
    "IssueView",
    "LegendChoiceView",
    "LegendMetaView",
    "MetaDeckView",
    "MetaStatusView",
    "PairingView",
    "PerformanceBasisView",
    "PerformanceView",
    "PrintingView",
    "ProposalView",
    "ProvenanceView",
    "QuestionView",
    "RankView",
    "RefreshRunView",
    "RefreshStatusView",
    "RepairDeckCardView",
    "RepairView",
    "RequirementRowView",
    "SaveCollectionRequest",
    "SaveCollectionResult",
    "ScoreView",
    "SmartSessionView",
    "SourceHealthView",
    "StartSessionRequest",
    "StrictRequest",
    "SuggestionView",
    "SwapView",
    "TournamentDetailView",
    "TournamentEntityView",
    "TournamentView",
    "TrendDeckView",
    "TrendOverviewView",
    "TrendPointView",
    "TrendSeriesView",
    "ValidationView",
]
